name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release - ${{ matrix.platform.target }}
    strategy:
      matrix:
        platform:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest
    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - name: Build and Upload
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: hammurabi
          target: ${{ matrix.platform.target }}
          archive: hammurabi-$target
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}